// Predefined Indian cities for listings (dropdown only — no free text, no geolocation).
// value is what's stored on the listing & matched in filters; label is shown to users.
// Coaching/exam hubs (Kota, Sikar, Prayagraj, Delhi) are intentionally included.
export const CITIES = [
  { value: 'Kota', label: 'Kota' },
  { value: 'Delhi', label: 'Delhi' },
  { value: 'New Delhi', label: 'New Delhi' },
  { value: 'Noida', label: 'Noida' },
  { value: 'Gurugram', label: 'Gurugram' },
  { value: 'Ghaziabad', label: 'Ghaziabad' },
  { value: 'Faridabad', label: 'Faridabad' },
  { value: 'Mumbai', label: 'Mumbai' },
  { value: 'Navi Mumbai', label: 'Navi Mumbai' },
  { value: 'Thane', label: 'Thane' },
  { value: 'Pune', label: 'Pune' },
  { value: 'Nagpur', label: 'Nagpur' },
  { value: 'Nashik', label: 'Nashik' },
  { value: 'Bengaluru', label: 'Bengaluru' },
  { value: 'Mysuru', label: 'Mysuru' },
  { value: 'Hyderabad', label: 'Hyderabad' },
  { value: 'Warangal', label: 'Warangal' },
  { value: 'Chennai', label: 'Chennai' },
  { value: 'Coimbatore', label: 'Coimbatore' },
  { value: 'Madurai', label: 'Madurai' },
  { value: 'Kolkata', label: 'Kolkata' },
  { value: 'Siliguri', label: 'Siliguri' },
  { value: 'Durgapur', label: 'Durgapur' },
  { value: 'Ahmedabad', label: 'Ahmedabad' },
  { value: 'Surat', label: 'Surat' },
  { value: 'Vadodara', label: 'Vadodara' },
  { value: 'Rajkot', label: 'Rajkot' },
  { value: 'Jaipur', label: 'Jaipur' },
  { value: 'Sikar', label: 'Sikar' },
  { value: 'Jodhpur', label: 'Jodhpur' },
  { value: 'Udaipur', label: 'Udaipur' },
  { value: 'Ajmer', label: 'Ajmer' },
  { value: 'Lucknow', label: 'Lucknow' },
  { value: 'Kanpur', label: 'Kanpur' },
  { value: 'Prayagraj', label: 'Prayagraj (Allahabad)' },
  { value: 'Varanasi', label: 'Varanasi' },
  { value: 'Meerut', label: 'Meerut' },
  { value: 'Agra', label: 'Agra' },
  { value: 'Gorakhpur', label: 'Gorakhpur' },
  { value: 'Indore', label: 'Indore' },
  { value: 'Bhopal', label: 'Bhopal' },
  { value: 'Gwalior', label: 'Gwalior' },
  { value: 'Jabalpur', label: 'Jabalpur' },
  { value: 'Patna', label: 'Patna' },
  { value: 'Ranchi', label: 'Ranchi' },
  { value: 'Jamshedpur', label: 'Jamshedpur' },
  { value: 'Dhanbad', label: 'Dhanbad' },
  { value: 'Raipur', label: 'Raipur' },
  { value: 'Bhubaneswar', label: 'Bhubaneswar' },
  { value: 'Guwahati', label: 'Guwahati' },
  { value: 'Chandigarh', label: 'Chandigarh' },
  { value: 'Amritsar', label: 'Amritsar' },
  { value: 'Ludhiana', label: 'Ludhiana' },
  { value: 'Jalandhar', label: 'Jalandhar' },
  { value: 'Dehradun', label: 'Dehradun' },
  { value: 'Shimla', label: 'Shimla' },
  { value: 'Jammu', label: 'Jammu' },
  { value: 'Srinagar', label: 'Srinagar' },
  { value: 'Visakhapatnam', label: 'Visakhapatnam' },
  { value: 'Vijayawada', label: 'Vijayawada' },
  { value: 'Guntur', label: 'Guntur' },
  { value: 'Tirupati', label: 'Tirupati' },
  { value: 'Kochi', label: 'Kochi' },
  { value: 'Thiruvananthapuram', label: 'Thiruvananthapuram' },
  { value: 'Kozhikode', label: 'Kozhikode' },
  { value: 'Thrissur', label: 'Thrissur' },
]
