export const EXAM_CATEGORIES = [
  { value: 'JEE_MAINS', label: 'JEE Mains' },
  { value: 'JEE_ADVANCED', label: 'JEE Advanced' },
  { value: 'NEET_UG', label: 'NEET UG' },
  { value: 'NEET_PG', label: 'NEET PG' },
  { value: 'UPSC_CSE', label: 'UPSC CSE' },
  { value: 'UPSC_OTHER', label: 'UPSC Other' },
  { value: 'CA_FOUNDATION', label: 'CA Foundation' },
  { value: 'CA_INTERMEDIATE', label: 'CA Intermediate' },
  { value: 'CA_FINAL', label: 'CA Final' },
  { value: 'GATE', label: 'GATE' },
  { value: 'GMAT', label: 'GMAT' },
  { value: 'GRE', label: 'GRE' },
  { value: 'IELTS', label: 'IELTS' },
  { value: 'CUET', label: 'CUET' },
  { value: 'CLASS_9', label: 'Class 9' },
  { value: 'CLASS_10', label: 'Class 10' },
  { value: 'CLASS_11', label: 'Class 11' },
  { value: 'CLASS_12', label: 'Class 12' },
  { value: 'OTHER', label: 'Other' },
]
