// Suggested subjects for the create-listing combobox. Free text is allowed —
// these are <datalist> defaults, not an enforced enum (subject variety across
// Indian exam material is too wide to lock down).
export const SUBJECTS = [
  'Physics',
  'Chemistry',
  'Physical Chemistry',
  'Organic Chemistry',
  'Inorganic Chemistry',
  'Mathematics',
  'Biology',
  'Botany',
  'Zoology',
  'English',
  'Reasoning',
  'Logical Reasoning',
  'Quantitative Aptitude',
  'Data Interpretation',
  'Verbal Ability',
  'General Knowledge',
  'Current Affairs',
  'General Studies',
  'History',
  'Geography',
  'Polity',
  'Indian Economy',
  'Environment & Ecology',
  'Science & Technology',
  'Ethics',
  'Accountancy',
  'Cost & Management Accounting',
  'Taxation',
  'Auditing',
  'Financial Management',
  'Corporate & Business Law',
  'Economics',
  'Computer Science',
  'Engineering Mathematics',
  'Aptitude',
  'Multiple subjects',
]
