const SITE_URL = 'https://nextprep.online'

/**
 * robots.txt — generated by Next.js Metadata Route.
 * Public marketplace pages are crawlable; account, auth and write-flows are
 * disallowed (private, behind login, or thin) to keep them out of the index.
 */
export default function robots() {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/dashboard',
          '/settings',
          '/chat/',
          '/transactions/',
          '/sell/',
          '/listings/new',
          '/login',
          '/auth/',
          '/api/',
        ],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  }
}
