"""Add colleges table + college_id/college_other on listings & users

Creates a canonical `colleges` reference table (unique slug + name) and adds a
nullable `college_id` FK + free-text `college_other` fallback to both `listings`
and `public.users`. `ON DELETE SET NULL` means retiring a college never deletes a
listing or user. The canonical campus list is seeded here and grows later via the
Supabase dashboard (no code deploy needed). No backfill of existing rows — college
is new and optional, so legacy rows stay NULL until the owner edits them (same as
`state` in 0011).

Revision ID: 0012
Revises: 0011
Create Date: 2026-06-28
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

revision = "0012"
down_revision = "0011"
branch_labels = None
depends_on = None

# (slug, name, state, district) — seed list; the 4th element (district) is stored
# in colleges.city. Source/curation: see spec §"Seeding".
COLLEGES_SEED = [
    ("als-ias-delhi", "ALS IAS (Delhi)", "Delhi", "New Delhi"),
    ("aakash-institute-delhi", "Aakash Institute (Delhi)", "Delhi", "New Delhi"),
    ("akash-byju-s-delhi", "Akash Byju's (Delhi)", "Delhi", "New Delhi"),
    ("aldine-ca-delhi", "Aldine CA (Delhi)", "Delhi", "New Delhi"),
    ("allen-career-institute-kota", "Allen Career Institute (Kota)", "Rajasthan", "Kota"),
    ("analog-ias-hyderabad", "Analog IAS (Hyderabad)", "Telangana", "Hyderabad"),
    ("base-educational-services-bengaluru", "BASE Educational Services (Bengaluru)", "Karnataka", "Bengaluru Urban"),
    ("byju-s", "BYJU'S", "Karnataka", "Bengaluru Urban"),
    ("bansal-classes-kota", "Bansal Classes (Kota)", "Rajasthan", "Kota"),
    ("career-launcher-delhi", "Career Launcher (Delhi)", "Delhi", "New Delhi"),
    ("career-point-kota", "Career Point (Kota)", "Rajasthan", "Kota"),
    ("chanakya-ias-academy-delhi", "Chanakya IAS Academy (Delhi)", "Delhi", "New Delhi"),
    ("deeksha-bengaluru", "Deeksha (Bengaluru)", "Karnataka", "Bengaluru Urban"),
    ("drishti-ias-delhi", "Drishti IAS (Delhi)", "Delhi", "North"),
    ("fiitjee-delhi", "FIITJEE (Delhi)", "Delhi", "South"),
    ("forum-ias-delhi", "Forum IAS (Delhi)", "Delhi", "New Delhi"),
    ("gs-score-delhi", "GS Score (Delhi)", "Delhi", "New Delhi"),
    ("icai-new-delhi", "ICAI (New Delhi)", "Delhi", "New Delhi"),
    ("ims-learning-mumbai", "IMS Learning (Mumbai)", "Maharashtra", "Mumbai"),
    ("insights-ias-bengaluru", "Insights IAS (Bengaluru)", "Karnataka", "Bengaluru Urban"),
    ("jk-shah-classes-mumbai", "JK Shah Classes (Mumbai)", "Maharashtra", "Mumbai"),
    ("khan-study-group-delhi", "Khan Study Group (Delhi)", "Delhi", "New Delhi"),
    ("la-excellence-ias-hyderabad", "La Excellence IAS (Hyderabad)", "Telangana", "Hyderabad"),
    ("motion-education-kota", "Motion Education (Kota)", "Rajasthan", "Kota"),
    ("narayana-hyderabad", "Narayana (Hyderabad)", "Telangana", "Hyderabad"),
    ("narayana-iit-academy-delhi", "Narayana IIT Academy (Delhi)", "Delhi", "New Delhi"),
    ("navkar-institute-ahmedabad", "Navkar Institute (Ahmedabad)", "Gujarat", "Ahmedabad"),
    ("next-ias-delhi", "Next IAS (Delhi)", "Delhi", "New Delhi"),
    ("nucleus-education-kota", "Nucleus Education (Kota)", "Rajasthan", "Kota"),
    ("pw-vidyapeeth-kota", "PW Vidyapeeth (Kota)", "Rajasthan", "Kota"),
    ("pace-iit-and-medical-mumbai", "Pace IIT & Medical (Mumbai)", "Maharashtra", "Mumbai"),
    ("physics-wallah-noida", "Physics Wallah (Noida)", "Uttar Pradesh", "Gautam Buddha Nagar"),
    ("plutus-ias-delhi", "Plutus IAS (Delhi)", "Delhi", "New Delhi"),
    ("reliable-institute-kota", "Reliable Institute (Kota)", "Rajasthan", "Kota"),
    ("resonance-kota", "Resonance (Kota)", "Rajasthan", "Kota"),
    ("shankar-ias-academy-chennai", "Shankar IAS Academy (Chennai)", "Tamil Nadu", "Chennai"),
    ("sri-chaitanya-hyderabad", "Sri Chaitanya (Hyderabad)", "Telangana", "Hyderabad"),
    ("t-i-m-e-hyderabad", "T.I.M.E. (Hyderabad)", "Telangana", "Hyderabad"),
    ("unacademy", "Unacademy", "Karnataka", "Bengaluru Urban"),
    ("vsi-jaipur-ca", "VSI Jaipur (CA)", "Rajasthan", "Jaipur"),
    ("vajiram-and-ravi-delhi", "Vajiram & Ravi (Delhi)", "Delhi", "New Delhi"),
    ("vedantu", "Vedantu", "Karnataka", "Bengaluru Urban"),
    ("vibrant-academy-kota", "Vibrant Academy (Kota)", "Rajasthan", "Kota"),
    ("vidyamandir-classes-delhi", "Vidyamandir Classes (Delhi)", "Delhi", "New Delhi"),
    ("vision-ias-delhi", "Vision IAS (Delhi)", "Delhi", "New Delhi"),
    ("abv-iiitm-gwalior", "ABV-IIITM Gwalior", "Madhya Pradesh", "Gwalior"),
    ("anna-university", "Anna University", "Tamil Nadu", "Chennai"),
    ("bit-mesra", "BIT Mesra", "Jharkhand", "Ranchi"),
    ("bits-pilani", "BITS Pilani", "Rajasthan", "Jhunjhunu"),
    ("bits-pilani-goa-campus", "BITS Pilani (Goa Campus)", "Goa", "North Goa"),
    ("bits-pilani-hyderabad-campus", "BITS Pilani (Hyderabad Campus)", "Telangana", "Hyderabad"),
    ("bms-college-of-engineering-bmsce", "BMS College of Engineering (BMSCE)", "Karnataka", "Bengaluru Urban"),
    ("coep-pune", "COEP Pune", "Maharashtra", "Pune"),
    ("chaitanya-bharathi-institute-of-technology-cbit", "Chaitanya Bharathi Institute of Technology (CBIT)", "Telangana", "Hyderabad"),
    ("dtu-delhi-technological-university", "DTU (Delhi Technological University)", "Delhi", "North West"),
    ("dayananda-sagar-college-of-engineering-dsce", "Dayananda Sagar College of Engineering (DSCE)", "Karnataka", "Bengaluru Urban"),
    ("iiest-shibpur", "IIEST Shibpur", "West Bengal", "Howrah"),
    ("iiit-allahabad", "IIIT Allahabad", "Uttar Pradesh", "Prayagraj"),
    ("iiit-bangalore", "IIIT Bangalore", "Karnataka", "Bengaluru Urban"),
    ("iiit-bhagalpur", "IIIT Bhagalpur", "Bihar", "Bhagalpur"),
    ("iiit-bhopal", "IIIT Bhopal", "Madhya Pradesh", "Bhopal"),
    ("iiit-delhi", "IIIT Delhi", "Delhi", "South"),
    ("iiit-dharwad", "IIIT Dharwad", "Karnataka", "Dharwad"),
    ("iiit-guwahati", "IIIT Guwahati", "Assam", "Kamrup Metro"),
    ("iiit-hyderabad", "IIIT Hyderabad", "Telangana", "Hyderabad"),
    ("iiit-kalyani", "IIIT Kalyani", "West Bengal", "Nadia"),
    ("iiit-kota", "IIIT Kota", "Rajasthan", "Kota"),
    ("iiit-lucknow", "IIIT Lucknow", "Uttar Pradesh", "Lucknow"),
    ("iiit-manipur", "IIIT Manipur", "Manipur", "Imphal West"),
    ("iiit-nagpur", "IIIT Nagpur", "Maharashtra", "Nagpur"),
    ("iiit-pune", "IIIT Pune", "Maharashtra", "Pune"),
    ("iiit-ranchi", "IIIT Ranchi", "Jharkhand", "Ranchi"),
    ("iiit-sonepat", "IIIT Sonepat", "Haryana", "Sonipat"),
    ("iiit-sri-city", "IIIT Sri City", "Andhra Pradesh", "Tirupati"),
    ("iiit-surat", "IIIT Surat", "Gujarat", "Surat"),
    ("iiit-tiruchirappalli", "IIIT Tiruchirappalli", "Tamil Nadu", "Tiruchirappalli"),
    ("iiit-una", "IIIT Una", "Himachal Pradesh", "Una"),
    ("iiit-vadodara", "IIIT Vadodara", "Gujarat", "Gandhinagar"),
    ("iiitdm-jabalpur", "IIITDM Jabalpur", "Madhya Pradesh", "Jabalpur"),
    ("iiitdm-kancheepuram", "IIITDM Kancheepuram", "Tamil Nadu", "Kancheepuram"),
    ("iiitdm-kottayam", "IIITDM Kottayam", "Kerala", "Kottayam"),
    ("iiitdm-kurnool", "IIITDM Kurnool", "Andhra Pradesh", "Kurnool"),
    ("iiser-berhampur", "IISER Berhampur", "Odisha", "Ganjam"),
    ("iiser-bhopal", "IISER Bhopal", "Madhya Pradesh", "Bhopal"),
    ("iiser-kolkata", "IISER Kolkata", "West Bengal", "Nadia"),
    ("iiser-mohali", "IISER Mohali", "Punjab", "S.A.S Nagar"),
    ("iiser-pune", "IISER Pune", "Maharashtra", "Pune"),
    ("iiser-thiruvananthapuram", "IISER Thiruvananthapuram", "Kerala", "Thiruvananthapuram"),
    ("iiser-tirupati", "IISER Tirupati", "Andhra Pradesh", "Tirupati"),
    ("iisc-bangalore", "IISc Bangalore", "Karnataka", "Bengaluru Urban"),
    ("iit-bhu-varanasi", "IIT BHU Varanasi", "Uttar Pradesh", "Varanasi"),
    ("iit-bhilai", "IIT Bhilai", "Chhattisgarh", "Durg"),
    ("iit-bhubaneswar", "IIT Bhubaneswar", "Odisha", "Khordha"),
    ("iit-bombay", "IIT Bombay", "Maharashtra", "Mumbai"),
    ("iit-delhi", "IIT Delhi", "Delhi", "South West"),
    ("iit-dhanbad", "IIT Dhanbad", "Jharkhand", "Dhanbad"),
    ("iit-dharwad", "IIT Dharwad", "Karnataka", "Dharwad"),
    ("iit-gandhinagar", "IIT Gandhinagar", "Gujarat", "Gandhinagar"),
    ("iit-goa", "IIT Goa", "Goa", "South Goa"),
    ("iit-guwahati", "IIT Guwahati", "Assam", "Kamrup Metro"),
    ("iit-hyderabad", "IIT Hyderabad", "Telangana", "Sangareddy"),
    ("iit-indore", "IIT Indore", "Madhya Pradesh", "Indore"),
    ("iit-jammu", "IIT Jammu", "Jammu and Kashmir", "Jammu"),
    ("iit-jodhpur", "IIT Jodhpur", "Rajasthan", "Jodhpur"),
    ("iit-kanpur", "IIT Kanpur", "Uttar Pradesh", "Kanpur Nagar"),
    ("iit-kharagpur", "IIT Kharagpur", "West Bengal", "Paschim Medinipur"),
    ("iit-madras", "IIT Madras", "Tamil Nadu", "Chennai"),
    ("iit-mandi", "IIT Mandi", "Himachal Pradesh", "Mandi"),
    ("iit-palakkad", "IIT Palakkad", "Kerala", "Palakkad"),
    ("iit-patna", "IIT Patna", "Bihar", "Patna"),
    ("iit-roorkee", "IIT Roorkee", "Uttarakhand", "Haridwar"),
    ("iit-ropar", "IIT Ropar", "Punjab", "Rupnagar"),
    ("iit-tirupati", "IIT Tirupati", "Andhra Pradesh", "Tirupati"),
    ("jadavpur-university", "Jadavpur University", "West Bengal", "Kolkata"),
    ("jaypee-institute-of-information-technology-jiit-noida", "Jaypee Institute of Information Technology (JIIT Noida)", "Uttar Pradesh", "Gautam Buddha Nagar"),
    ("m-s-ramaiah-institute-of-technology-msrit", "M S Ramaiah Institute of Technology (MSRIT)", "Karnataka", "Bengaluru Urban"),
    ("manit-bhopal", "MANIT Bhopal", "Madhya Pradesh", "Bhopal"),
    ("mnit-jaipur", "MNIT Jaipur", "Rajasthan", "Jaipur"),
    ("mnnit-allahabad", "MNNIT Allahabad", "Uttar Pradesh", "Prayagraj"),
    ("manipal-institute-of-technology-mit-manipal", "Manipal Institute of Technology (MIT Manipal)", "Karnataka", "Udupi"),
    ("nit-agartala", "NIT Agartala", "Tripura", "West Tripura"),
    ("nit-andhra-pradesh", "NIT Andhra Pradesh", "Andhra Pradesh", "West Godavari"),
    ("nit-arunachal-pradesh", "NIT Arunachal Pradesh", "Arunachal Pradesh", "Papum Pare"),
    ("nit-calicut", "NIT Calicut", "Kerala", "Kozhikode"),
    ("nit-delhi", "NIT Delhi", "Delhi", "North West"),
    ("nit-durgapur", "NIT Durgapur", "West Bengal", "Paschim Bardhaman"),
    ("nit-goa", "NIT Goa", "Goa", "South Goa"),
    ("nit-hamirpur", "NIT Hamirpur", "Himachal Pradesh", "Hamirpur"),
    ("nit-jalandhar", "NIT Jalandhar", "Punjab", "Jalandhar"),
    ("nit-jamia-hamdard", "NIT Jamia (Hamdard)", "Delhi", "South"),
    ("nit-jamshedpur", "NIT Jamshedpur", "Jharkhand", "East Singhbum"),
    ("nit-kurukshetra", "NIT Kurukshetra", "Haryana", "Kurukshetra"),
    ("nit-manipur", "NIT Manipur", "Manipur", "Imphal West"),
    ("nit-meghalaya", "NIT Meghalaya", "Meghalaya", "East Khasi Hills"),
    ("nit-mizoram", "NIT Mizoram", "Mizoram", "Aizawl"),
    ("nit-nagaland", "NIT Nagaland", "Nagaland", "Dimapur"),
    ("nit-patna", "NIT Patna", "Bihar", "Patna"),
    ("nit-puducherry", "NIT Puducherry", "Puducherry", "Karaikal"),
    ("nit-raipur", "NIT Raipur", "Chhattisgarh", "Raipur"),
    ("nit-rourkela", "NIT Rourkela", "Odisha", "Sundargarh"),
    ("nit-sikkim", "NIT Sikkim", "Sikkim", "Namchi"),
    ("nit-silchar", "NIT Silchar", "Assam", "Cachar"),
    ("nit-srinagar", "NIT Srinagar", "Jammu and Kashmir", "Srinagar"),
    ("nit-surathkal", "NIT Surathkal", "Karnataka", "Dakshina Kannada"),
    ("nit-trichy", "NIT Trichy", "Tamil Nadu", "Tiruchirappalli"),
    ("nit-uttarakhand", "NIT Uttarakhand", "Uttarakhand", "Pauri Garhwal"),
    ("nit-warangal", "NIT Warangal", "Telangana", "Warangal"),
    ("nsut-netaji-subhas-university-of-technology", "NSUT (Netaji Subhas University of Technology)", "Delhi", "West"),
    ("pec-chandigarh", "PEC Chandigarh", "Chandigarh", "Chandigarh"),
    ("pes-university", "PES University", "Karnataka", "Bengaluru Urban"),
    ("psg-college-of-technology", "PSG College of Technology", "Tamil Nadu", "Coimbatore"),
    ("rv-college-of-engineering-rvce", "RV College of Engineering (RVCE)", "Karnataka", "Bengaluru Urban"),
    ("srm-institute-of-science-and-technology-kattankulathur", "SRM Institute of Science and Technology (Kattankulathur)", "Tamil Nadu", "Chengalpattu"),
    ("srm-university-ap", "SRM University AP", "Andhra Pradesh", "Guntur"),
    ("ssn-college-of-engineering", "SSN College of Engineering", "Tamil Nadu", "Chengalpattu"),
    ("svnit-surat", "SVNIT Surat", "Gujarat", "Surat"),
    ("symbiosis-institute-of-technology-pune", "Symbiosis Institute of Technology, Pune", "Maharashtra", "Pune"),
    ("thapar-institute", "Thapar Institute", "Punjab", "Patiala"),
    ("vit-bhopal-university", "VIT Bhopal University", "Madhya Pradesh", "Sehore"),
    ("vit-chennai", "VIT Chennai", "Tamil Nadu", "Chennai"),
    ("vit-vellore", "VIT Vellore", "Tamil Nadu", "Vellore"),
    ("vit-ap-university", "VIT-AP University", "Andhra Pradesh", "Guntur"),
    ("vjti-mumbai", "VJTI Mumbai", "Maharashtra", "Mumbai"),
    ("vnit-nagpur", "VNIT Nagpur", "Maharashtra", "Nagpur"),
    ("vnr-vignana-jyothi-institute-of-engineering-and-technology", "VNR Vignana Jyothi Institute of Engineering and Technology", "Telangana", "Hyderabad"),
    ("vasavi-college-of-engineering", "Vasavi College of Engineering", "Telangana", "Hyderabad"),
    ("cnlu-patna", "CNLU Patna", "Bihar", "Patna"),
    ("christ-university-school-of-law-bangalore", "Christ University School of Law, Bangalore", "Karnataka", "Bengaluru Urban"),
    ("dnlu-jabalpur", "DNLU Jabalpur", "Madhya Pradesh", "Jabalpur"),
    ("dsnlu-visakhapatnam", "DSNLU Visakhapatnam", "Andhra Pradesh", "Visakhapatnam"),
    ("faculty-of-law-delhi-university", "Faculty of Law, Delhi University", "Delhi", "North"),
    ("gnlu-gandhinagar", "GNLU Gandhinagar", "Gujarat", "Gandhinagar"),
    ("government-law-college-mumbai", "Government Law College, Mumbai", "Maharashtra", "Mumbai"),
    ("hnlu-raipur", "HNLU Raipur", "Chhattisgarh", "Raipur"),
    ("hpnlu-shimla", "HPNLU Shimla", "Himachal Pradesh", "Shimla"),
    ("ils-law-college-pune", "ILS Law College, Pune", "Maharashtra", "Pune"),
    ("jindal-global-law-school", "Jindal Global Law School", "Haryana", "Sonipat"),
    ("mnlu-mumbai", "MNLU Mumbai", "Maharashtra", "Mumbai Suburban"),
    ("mnlu-nagpur", "MNLU Nagpur", "Maharashtra", "Nagpur"),
    ("nalsar-hyderabad", "NALSAR Hyderabad", "Telangana", "Ranga Reddy"),
    ("nliu-bhopal", "NLIU Bhopal", "Madhya Pradesh", "Bhopal"),
    ("nlsiu-bangalore", "NLSIU Bangalore", "Karnataka", "Bengaluru Urban"),
    ("nlu-delhi", "NLU Delhi", "Delhi", "South West"),
    ("nlu-jodhpur", "NLU Jodhpur", "Rajasthan", "Jodhpur"),
    ("nluja-assam", "NLUJA Assam", "Assam", "Kamrup Metro"),
    ("nluo-cuttack", "NLUO Cuttack", "Odisha", "Cuttack"),
    ("nlut-tripura", "NLUT Tripura", "Tripura", "West Tripura"),
    ("nmims-school-of-law-mumbai", "NMIMS School of Law, Mumbai", "Maharashtra", "Mumbai Suburban"),
    ("nuals-kochi", "NUALS Kochi", "Kerala", "Ernakulam"),
    ("nujs-kolkata", "NUJS Kolkata", "West Bengal", "Kolkata"),
    ("nusrl-ranchi", "NUSRL Ranchi", "Jharkhand", "Ranchi"),
    ("rgnul-patiala", "RGNUL Patiala", "Punjab", "Patiala"),
    ("rmlnlu-lucknow", "RMLNLU Lucknow", "Uttar Pradesh", "Lucknow"),
    ("symbiosis-law-school-pune", "Symbiosis Law School, Pune", "Maharashtra", "Pune"),
    ("tnnlu-tiruchirappalli", "TNNLU Tiruchirappalli", "Tamil Nadu", "Tiruchirappalli"),
    ("doms-iit-bombay-sjmsom", "DoMS IIT Bombay (SJMSOM)", "Maharashtra", "Mumbai Suburban"),
    ("doms-iit-delhi", "DoMS IIT Delhi", "Delhi", "South"),
    ("doms-iit-kharagpur-vgsom", "DoMS IIT Kharagpur (VGSoM)", "West Bengal", "Paschim Medinipur"),
    ("doms-iit-madras", "DoMS IIT Madras", "Tamil Nadu", "Chennai"),
    ("doms-iit-roorkee", "DoMS IIT Roorkee", "Uttarakhand", "Haridwar"),
    ("fms-delhi", "FMS Delhi", "Delhi", "South"),
    ("great-lakes-institute-of-management-chennai", "Great Lakes Institute of Management Chennai", "Tamil Nadu", "Chengalpattu"),
    ("iift-delhi", "IIFT Delhi", "Delhi", "South"),
    ("iim-ahmedabad", "IIM Ahmedabad", "Gujarat", "Ahmedabad"),
    ("iim-amritsar", "IIM Amritsar", "Punjab", "Amritsar"),
    ("iim-bangalore", "IIM Bangalore", "Karnataka", "Bengaluru Urban"),
    ("iim-bodh-gaya", "IIM Bodh Gaya", "Bihar", "Gaya"),
    ("iim-calcutta", "IIM Calcutta", "West Bengal", "South 24 Parganas"),
    ("iim-indore", "IIM Indore", "Madhya Pradesh", "Indore"),
    ("iim-jammu", "IIM Jammu", "Jammu and Kashmir", "Jammu"),
    ("iim-kashipur", "IIM Kashipur", "Uttarakhand", "Udham Singh Nagar"),
    ("iim-kozhikode", "IIM Kozhikode", "Kerala", "Kozhikode"),
    ("iim-lucknow", "IIM Lucknow", "Uttar Pradesh", "Lucknow"),
    ("iim-mumbai", "IIM Mumbai", "Maharashtra", "Mumbai"),
    ("iim-nagpur", "IIM Nagpur", "Maharashtra", "Nagpur"),
    ("iim-raipur", "IIM Raipur", "Chhattisgarh", "Raipur"),
    ("iim-ranchi", "IIM Ranchi", "Jharkhand", "Ranchi"),
    ("iim-rohtak", "IIM Rohtak", "Haryana", "Rohtak"),
    ("iim-sambalpur", "IIM Sambalpur", "Odisha", "Sambalpur"),
    ("iim-shillong", "IIM Shillong", "Meghalaya", "East Khasi Hills"),
    ("iim-sirmaur", "IIM Sirmaur", "Himachal Pradesh", "Sirmaur"),
    ("iim-tiruchirappalli", "IIM Tiruchirappalli", "Tamil Nadu", "Tiruchirappalli"),
    ("iim-udaipur", "IIM Udaipur", "Rajasthan", "Udaipur"),
    ("iim-visakhapatnam", "IIM Visakhapatnam", "Andhra Pradesh", "Visakhapatnam"),
    ("imi-delhi", "IMI Delhi", "Delhi", "South West"),
    ("imt-ghaziabad", "IMT Ghaziabad", "Uttar Pradesh", "Ghaziabad"),
    ("isb-hyderabad", "ISB Hyderabad", "Telangana", "Hyderabad"),
    ("isb-mohali", "ISB Mohali", "Punjab", "S.A.S Nagar"),
    ("jbims-mumbai", "JBIMS Mumbai", "Maharashtra", "Mumbai"),
    ("mdi-gurgaon", "MDI Gurgaon", "Haryana", "Gurugram"),
    ("mica-ahmedabad", "MICA Ahmedabad", "Gujarat", "Ahmedabad"),
    ("sibm-pune", "SIBM Pune", "Maharashtra", "Pune"),
    ("spjimr-mumbai", "SPJIMR Mumbai", "Maharashtra", "Mumbai"),
    ("tapmi-manipal", "TAPMI Manipal", "Karnataka", "Udupi"),
    ("ximb-xim-university-bhubaneswar", "XIMB (XIM University) Bhubaneswar", "Odisha", "Khordha"),
    ("xlri-jamshedpur", "XLRI Jamshedpur", "Jharkhand", "East Singhbum"),
    ("afmc-pune", "AFMC Pune", "Maharashtra", "Pune"),
    ("aiims-bathinda", "AIIMS Bathinda", "Punjab", "Bathinda"),
    ("aiims-bhopal", "AIIMS Bhopal", "Madhya Pradesh", "Bhopal"),
    ("aiims-bhubaneswar", "AIIMS Bhubaneswar", "Odisha", "Khordha"),
    ("aiims-bibinagar", "AIIMS Bibinagar", "Telangana", "Yadadri Bhuvanagiri"),
    ("aiims-bilaspur", "AIIMS Bilaspur", "Himachal Pradesh", "Bilaspur"),
    ("aiims-delhi", "AIIMS Delhi", "Delhi", "South"),
    ("aiims-deoghar", "AIIMS Deoghar", "Jharkhand", "Deoghar"),
    ("aiims-gorakhpur", "AIIMS Gorakhpur", "Uttar Pradesh", "Gorakhpur"),
    ("aiims-guwahati", "AIIMS Guwahati", "Assam", "Kamrup Metro"),
    ("aiims-jodhpur", "AIIMS Jodhpur", "Rajasthan", "Jodhpur"),
    ("aiims-kalyani", "AIIMS Kalyani", "West Bengal", "Nadia"),
    ("aiims-madurai", "AIIMS Madurai", "Tamil Nadu", "Madurai"),
    ("aiims-mangalagiri", "AIIMS Mangalagiri", "Andhra Pradesh", "Guntur"),
    ("aiims-nagpur", "AIIMS Nagpur", "Maharashtra", "Nagpur"),
    ("aiims-patna", "AIIMS Patna", "Bihar", "Patna"),
    ("aiims-raebareli", "AIIMS Raebareli", "Uttar Pradesh", "Rae Bareli"),
    ("aiims-raipur", "AIIMS Raipur", "Chhattisgarh", "Raipur"),
    ("aiims-rajkot", "AIIMS Rajkot", "Gujarat", "Rajkot"),
    ("aiims-rishikesh", "AIIMS Rishikesh", "Uttarakhand", "Dehradun"),
    ("aiims-vijaypur-jammu", "AIIMS Vijaypur (Jammu)", "Jammu and Kashmir", "Samba"),
    ("amrita-institute-of-medical-sciences-kochi", "Amrita Institute of Medical Sciences, Kochi", "Kerala", "Ernakulam"),
    ("andhra-medical-college-visakhapatnam", "Andhra Medical College, Visakhapatnam", "Andhra Pradesh", "Visakhapatnam"),
    ("bj-medical-college-ahmedabad", "BJ Medical College, Ahmedabad", "Gujarat", "Ahmedabad"),
    ("bj-medical-college-pune", "BJ Medical College, Pune", "Maharashtra", "Pune"),
    ("bangalore-medical-college", "Bangalore Medical College", "Karnataka", "Bengaluru Urban"),
    ("cmc-ludhiana", "CMC Ludhiana", "Punjab", "Ludhiana"),
    ("cmc-vellore", "CMC Vellore", "Tamil Nadu", "Vellore"),
    ("coimbatore-medical-college", "Coimbatore Medical College", "Tamil Nadu", "Coimbatore"),
    ("dy-patil-medical-college-pune", "DY Patil Medical College, Pune", "Maharashtra", "Pune"),
    ("gandhi-medical-college-bhopal", "Gandhi Medical College, Bhopal", "Madhya Pradesh", "Bhopal"),
    ("gandhi-medical-college-hyderabad", "Gandhi Medical College, Hyderabad", "Telangana", "Hyderabad"),
    ("government-medical-college-amritsar", "Government Medical College, Amritsar", "Punjab", "Amritsar"),
    ("government-medical-college-chandigarh-gmch", "Government Medical College, Chandigarh (GMCH)", "Chandigarh", "Chandigarh"),
    ("government-medical-college-kota", "Government Medical College, Kota", "Rajasthan", "Kota"),
    ("government-medical-college-kozhikode", "Government Medical College, Kozhikode", "Kerala", "Kozhikode"),
    ("government-medical-college-nagpur", "Government Medical College, Nagpur", "Maharashtra", "Nagpur"),
    ("government-medical-college-srinagar", "Government Medical College, Srinagar", "Jammu and Kashmir", "Srinagar"),
    ("government-medical-college-surat", "Government Medical College, Surat", "Gujarat", "Surat"),
    ("government-medical-college-thiruvananthapuram", "Government Medical College, Thiruvananthapuram", "Kerala", "Thiruvananthapuram"),
    ("grant-medical-college-mumbai", "Grant Medical College, Mumbai", "Maharashtra", "Mumbai"),
    ("guntur-medical-college", "Guntur Medical College", "Andhra Pradesh", "Guntur"),
    ("institute-of-medical-sciences-bhu-varanasi", "Institute of Medical Sciences, BHU, Varanasi", "Uttar Pradesh", "Varanasi"),
    ("jipmer-puducherry", "JIPMER Puducherry", "Puducherry", "Puducherry"),
    ("jss-medical-college-mysore", "JSS Medical College, Mysore", "Karnataka", "Mysuru"),
    ("jawaharlal-nehru-medical-college-aligarh-amu", "Jawaharlal Nehru Medical College, Aligarh (AMU)", "Uttar Pradesh", "Aligarh"),
    ("kgmu-lucknow", "KGMU Lucknow", "Uttar Pradesh", "Lucknow"),
    ("kasturba-hospital-gsl-medical-college-christian-medical-jubilee", "Kasturba Hospital / GSL Medical College — Christian Medical, Jubilee", "Andhra Pradesh", "East Godavari"),
    ("kasturba-medical-ms-ramaiah-medical-college-bangalore", "Kasturba Medical / MS Ramaiah Medical College, Bangalore", "Karnataka", "Bengaluru Urban"),
    ("kasturba-medical-college-jamia-hamdard-alt-jnmc-belagavi", "Kasturba Medical College (Jamia Hamdard alt) — JNMC Belagavi", "Karnataka", "Belagavi"),
    ("kasturba-medical-college-mangalore", "Kasturba Medical College, Mangalore", "Karnataka", "Dakshina Kannada"),
    ("kasturba-medical-college-manipal", "Kasturba Medical College, Manipal", "Karnataka", "Udupi"),
    ("kilpauk-medical-college-chennai", "Kilpauk Medical College, Chennai", "Tamil Nadu", "Chennai"),
    ("king-george-s-medical-university-lucknow", "King George's Medical University, Lucknow", "Uttar Pradesh", "Lucknow"),
    ("lady-hardinge-medical-college", "Lady Hardinge Medical College", "Delhi", "New Delhi"),
    ("lokmanya-tilak-medical-college-sion-mumbai", "Lokmanya Tilak Medical College (Sion), Mumbai", "Maharashtra", "Mumbai"),
    ("madras-medical-college", "Madras Medical College", "Tamil Nadu", "Chennai"),
    ("maharashtra-institute-of-medical-education-mimer-bharati-vidyapeeth-medical-college-pune", "Maharashtra Institute of Medical Education (MIMER) / Bharati Vidyapeeth Medical College, Pune", "Maharashtra", "Pune"),
    ("mahatma-gandhi-memorial-medical-college-indore", "Mahatma Gandhi Memorial Medical College, Indore", "Madhya Pradesh", "Indore"),
    ("manipal-college-of-dental-sciences-manipal", "Manipal College of Dental Sciences, Manipal", "Karnataka", "Udupi"),
    ("maulana-azad-institute-of-dental-sciences-delhi", "Maulana Azad Institute of Dental Sciences, Delhi", "Delhi", "Central"),
    ("maulana-azad-medical-college", "Maulana Azad Medical College", "Delhi", "Central"),
    ("medical-college-kolkata", "Medical College, Kolkata", "West Bengal", "Kolkata"),
    ("nilratan-sircar-medical-college-kolkata", "Nilratan Sircar Medical College, Kolkata", "West Bengal", "Kolkata"),
    ("osmania-medical-college-hyderabad", "Osmania Medical College, Hyderabad", "Telangana", "Hyderabad"),
    ("patna-medical-college", "Patna Medical College", "Bihar", "Patna"),
    ("pt-bd-sharma-pgims-rohtak", "Pt. BD Sharma PGIMS, Rohtak", "Haryana", "Rohtak"),
    ("rg-kar-medical-college-kolkata", "RG Kar Medical College, Kolkata", "West Bengal", "Kolkata"),
    ("scb-medical-college-cuttack", "SCB Medical College, Cuttack", "Odisha", "Cuttack"),
    ("sms-medical-college-jaipur", "SMS Medical College, Jaipur", "Rajasthan", "Jaipur"),
    ("srm-medical-college-chennai", "SRM Medical College, Chennai", "Tamil Nadu", "Chengalpattu"),
    ("sardar-patel-medical-college-bikaner", "Sardar Patel Medical College, Bikaner", "Rajasthan", "Bikaner"),
    ("seth-gs-medical-college-kem-mumbai", "Seth GS Medical College (KEM), Mumbai", "Maharashtra", "Mumbai"),
    ("sri-ramachandra-medical-college-chennai", "Sri Ramachandra Medical College, Chennai", "Tamil Nadu", "Chennai"),
    ("st-john-s-medical-college-bangalore", "St. John's Medical College, Bangalore", "Karnataka", "Bengaluru Urban"),
    ("stanley-medical-college-chennai", "Stanley Medical College, Chennai", "Tamil Nadu", "Chennai"),
    ("topiwala-national-medical-college-nair-mumbai", "Topiwala National Medical College (Nair), Mumbai", "Maharashtra", "Mumbai"),
    ("university-college-of-medical-sciences", "University College of Medical Sciences", "Delhi", "East"),
    ("vardhman-mahavir-medical-college-safdarjung", "Vardhman Mahavir Medical College (Safdarjung)", "Delhi", "South West"),
    ("amity-university-jaipur", "Amity University Jaipur", "Rajasthan", "Jaipur"),
    ("amity-university-mumbai", "Amity University Mumbai", "Maharashtra", "Mumbai"),
    ("amity-university-noida", "Amity University Noida", "Uttar Pradesh", "Gautam Buddha Nagar"),
    ("amrita-vishwa-vidyapeetham-amritapuri", "Amrita Vishwa Vidyapeetham (Amritapuri)", "Kerala", "Kollam"),
    ("amrita-vishwa-vidyapeetham-bengaluru", "Amrita Vishwa Vidyapeetham (Bengaluru)", "Karnataka", "Bengaluru Urban"),
    ("amrita-vishwa-vidyapeetham-coimbatore", "Amrita Vishwa Vidyapeetham (Coimbatore)", "Tamil Nadu", "Coimbatore"),
    ("ashoka-university", "Ashoka University", "Haryana", "Sonipat"),
    ("bennett-university", "Bennett University", "Uttar Pradesh", "Gautam Buddha Nagar"),
    ("chandigarh-university", "Chandigarh University", "Punjab", "S.A.S Nagar"),
    ("christ-university", "Christ University", "Karnataka", "Bengaluru Urban"),
    ("graphic-era-university", "Graphic Era University", "Uttarakhand", "Dehradun"),
    ("kalinga-institute-of-industrial-technology-kiit", "Kalinga Institute of Industrial Technology (KIIT)", "Odisha", "Khordha"),
    ("lovely-professional-university-lpu", "Lovely Professional University (LPU)", "Punjab", "Kapurthala"),
    ("manav-rachna-university", "Manav Rachna University", "Haryana", "Faridabad"),
    ("manipal-university-jaipur", "Manipal University Jaipur", "Rajasthan", "Jaipur"),
    ("nmims-mumbai", "NMIMS Mumbai", "Maharashtra", "Mumbai"),
    ("nirma-university", "Nirma University", "Gujarat", "Ahmedabad"),
    ("o-p-jindal-global-university", "O.P. Jindal Global University", "Haryana", "Sonipat"),
    ("sharda-university", "Sharda University", "Uttar Pradesh", "Gautam Buddha Nagar"),
    ("shiv-nadar-university", "Shiv Nadar University", "Uttar Pradesh", "Gautam Buddha Nagar"),
    ("symbiosis-international-university", "Symbiosis International University", "Maharashtra", "Pune"),
    ("university-of-petroleum-and-energy-studies-upes", "University of Petroleum and Energy Studies (UPES)", "Uttarakhand", "Dehradun"),
    ("aliah-university", "Aliah University", "West Bengal", "Kolkata"),
    ("aligarh-muslim-university", "Aligarh Muslim University", "Uttar Pradesh", "Aligarh"),
    ("andhra-university", "Andhra University", "Andhra Pradesh", "Visakhapatnam"),
    ("assam-university", "Assam University", "Assam", "Cachar"),
    ("banaras-hindu-university", "Banaras Hindu University", "Uttar Pradesh", "Varanasi"),
    ("bangalore-university", "Bangalore University", "Karnataka", "Bengaluru Urban"),
    ("bharathiar-university", "Bharathiar University", "Tamil Nadu", "Coimbatore"),
    ("central-university-of-gujarat", "Central University of Gujarat", "Gujarat", "Gandhinagar"),
    ("central-university-of-himachal-pradesh", "Central University of Himachal Pradesh", "Himachal Pradesh", "Kangra"),
    ("central-university-of-jammu", "Central University of Jammu", "Jammu and Kashmir", "Samba"),
    ("central-university-of-jharkhand", "Central University of Jharkhand", "Jharkhand", "Ranchi"),
    ("central-university-of-karnataka", "Central University of Karnataka", "Karnataka", "Kalaburagi"),
    ("central-university-of-kashmir", "Central University of Kashmir", "Jammu and Kashmir", "Ganderbal"),
    ("central-university-of-kerala", "Central University of Kerala", "Kerala", "Kasaragod"),
    ("central-university-of-odisha", "Central University of Odisha", "Odisha", "Koraput"),
    ("central-university-of-punjab", "Central University of Punjab", "Punjab", "Bathinda"),
    ("central-university-of-rajasthan", "Central University of Rajasthan", "Rajasthan", "Ajmer"),
    ("central-university-of-south-bihar", "Central University of South Bihar", "Bihar", "Gaya"),
    ("central-university-of-tamil-nadu", "Central University of Tamil Nadu", "Tamil Nadu", "Thiruvarur"),
    ("daulat-ram-college", "Daulat Ram College", "Delhi", "North"),
    ("devi-ahilya-vishwavidyalaya", "Devi Ahilya Vishwavidyalaya", "Madhya Pradesh", "Indore"),
    ("fergusson-college", "Fergusson College", "Maharashtra", "Pune"),
    ("gargi-college", "Gargi College", "Delhi", "South"),
    ("gauhati-university", "Gauhati University", "Assam", "Kamrup Metro"),
    ("gujarat-university", "Gujarat University", "Gujarat", "Ahmedabad"),
    ("hansraj-college", "Hansraj College", "Delhi", "North"),
    ("hemvati-nandan-bahuguna-garhwal-university", "Hemvati Nandan Bahuguna Garhwal University", "Uttarakhand", "Pauri Garhwal"),
    ("hindu-college", "Hindu College", "Delhi", "North"),
    ("indira-gandhi-national-open-university", "Indira Gandhi National Open University", "Delhi", "South"),
    ("jamia-millia-islamia", "Jamia Millia Islamia", "Delhi", "South East"),
    ("jawaharlal-nehru-university", "Jawaharlal Nehru University", "Delhi", "South West"),
    ("jesus-and-mary-college", "Jesus and Mary College", "Delhi", "South West"),
    ("kirori-mal-college", "Kirori Mal College", "Delhi", "North"),
    ("kurukshetra-university", "Kurukshetra University", "Haryana", "Kurukshetra"),
    ("lady-shri-ram-college-for-women", "Lady Shri Ram College for Women", "Delhi", "South"),
    ("loyola-college", "Loyola College", "Tamil Nadu", "Chennai"),
    ("mahatma-gandhi-central-university", "Mahatma Gandhi Central University", "Bihar", "Purbi Champaran"),
    ("manipur-university", "Manipur University", "Manipur", "Imphal West"),
    ("maulana-azad-national-urdu-university", "Maulana Azad National Urdu University", "Telangana", "Hyderabad"),
    ("miranda-house", "Miranda House", "Delhi", "North"),
    ("mizoram-university", "Mizoram University", "Mizoram", "Aizawl"),
    ("nagaland-university", "Nagaland University", "Nagaland", "Kohima"),
    ("nalanda-university", "Nalanda University", "Bihar", "Nalanda"),
    ("north-eastern-hill-university", "North-Eastern Hill University", "Meghalaya", "East Khasi Hills"),
    ("osmania-university", "Osmania University", "Telangana", "Hyderabad"),
    ("panjab-university", "Panjab University", "Chandigarh", "Chandigarh"),
    ("patna-university", "Patna University", "Bihar", "Patna"),
    ("pondicherry-university", "Pondicherry University", "Puducherry", "Puducherry"),
    ("presidency-college-chennai", "Presidency College, Chennai", "Tamil Nadu", "Chennai"),
    ("presidency-university-kolkata", "Presidency University, Kolkata", "West Bengal", "Kolkata"),
    ("rajiv-gandhi-university", "Rajiv Gandhi University", "Arunachal Pradesh", "Papum Pare"),
    ("ramjas-college", "Ramjas College", "Delhi", "North"),
    ("savitribai-phule-pune-university", "Savitribai Phule Pune University", "Maharashtra", "Pune"),
    ("shri-ram-college-of-commerce", "Shri Ram College of Commerce", "Delhi", "North"),
    ("sikkim-university", "Sikkim University", "Sikkim", "Gangtok"),
    ("sri-venkateswara-college", "Sri Venkateswara College", "Delhi", "South West"),
    ("st-joseph-s-university-bengaluru", "St. Joseph's University, Bengaluru", "Karnataka", "Bengaluru Urban"),
    ("st-stephen-s-college", "St. Stephen's College", "Delhi", "North"),
    ("st-xavier-s-college-kolkata", "St. Xavier's College, Kolkata", "West Bengal", "Kolkata"),
    ("st-xavier-s-college-mumbai", "St. Xavier's College, Mumbai", "Maharashtra", "Mumbai"),
    ("tezpur-university", "Tezpur University", "Assam", "Sonitpur"),
    ("tripura-university", "Tripura University", "Tripura", "West Tripura"),
    ("university-of-allahabad", "University of Allahabad", "Uttar Pradesh", "Prayagraj"),
    ("university-of-calcutta", "University of Calcutta", "West Bengal", "Kolkata"),
    ("university-of-delhi", "University of Delhi", "Delhi", "North"),
    ("university-of-hyderabad", "University of Hyderabad", "Telangana", "Hyderabad"),
    ("university-of-kerala", "University of Kerala", "Kerala", "Thiruvananthapuram"),
    ("university-of-lucknow", "University of Lucknow", "Uttar Pradesh", "Lucknow"),
    ("university-of-madras", "University of Madras", "Tamil Nadu", "Chennai"),
    ("university-of-mumbai", "University of Mumbai", "Maharashtra", "Mumbai"),
    ("university-of-mysore", "University of Mysore", "Karnataka", "Mysuru"),
    ("university-of-rajasthan", "University of Rajasthan", "Rajasthan", "Jaipur"),
    ("utkal-university", "Utkal University", "Odisha", "Khordha"),
    ("visva-bharati-university", "Visva-Bharati University", "West Bengal", "Birbhum"),
]


def upgrade() -> None:
    op.create_table(
        "colleges",
        sa.Column("id", UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("state", sa.String()),
        sa.Column("city", sa.String()),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.UniqueConstraint("slug", name="uq_college_slug"),
        sa.UniqueConstraint("name", name="uq_college_name"),
    )
    # Typeahead search hits name; filter resolves by slug.
    op.create_index("ix_colleges_name", "colleges", ["name"])

    # Nullable FK + free-text fallback on listings
    op.add_column("listings", sa.Column("college_id", UUID(as_uuid=True), nullable=True))
    op.add_column("listings", sa.Column("college_other", sa.String(), nullable=True))
    op.create_foreign_key("fk_listings_college", "listings", "colleges",
                          ["college_id"], ["id"], ondelete="SET NULL")
    op.create_index("ix_listings_college_id", "listings", ["college_id"])

    # Same on public.users (schema='public' — the one-table gotcha from 0011)
    op.add_column("users", sa.Column("college_id", UUID(as_uuid=True), nullable=True),
                  schema="public")
    op.add_column("users", sa.Column("college_other", sa.String(), nullable=True),
                  schema="public")
    op.create_foreign_key("fk_users_college", "users", "colleges",
                          ["college_id"], ["id"],
                          source_schema="public", ondelete="SET NULL")

    # Seed canonical colleges. Each tuple is (slug, name, state, district); the
    # district is stored in the colleges.city column.
    conn = op.get_bind()
    for slug, name, state, district in COLLEGES_SEED:
        conn.execute(
            sa.text("INSERT INTO colleges (slug, name, state, city) "
                    "VALUES (:slug, :name, :state, :city) ON CONFLICT (slug) DO NOTHING"),
            {"slug": slug, "name": name, "state": state, "city": district},
        )


def downgrade() -> None:
    op.drop_constraint("fk_users_college", "users", schema="public", type_="foreignkey")
    op.drop_column("users", "college_other", schema="public")
    op.drop_column("users", "college_id", schema="public")
    op.drop_constraint("fk_listings_college", "listings", type_="foreignkey")
    op.drop_index("ix_listings_college_id", table_name="listings")
    op.drop_column("listings", "college_other")
    op.drop_column("listings", "college_id")
    op.drop_index("ix_colleges_name", table_name="colleges")
    op.drop_table("colleges")
